/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package at.fhv.team-a.kartenverkauf;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
